dovecot_config_version = 2.4.1
dovecot_storage_version = 2.4.0

base_dir = /run/dovecot
state_dir = /run/dovecot

protocols = imap submission lmtp sieve pop3

mail_driver=maildir
mailbox_list_layout=index
mailbox_list_utf8=yes
mail_path=~/mail
mail_home=/srv/vmail/%{user | lower}
mail_utf8_extensions = yes

mail_uid = vmail
mail_gid = vmail

# Setup default mailboxes for inbox namespace
@mailbox_defaults = english

namespace inbox {
  separator = /
}

ssl_server {
  cert_file = /etc/dovecot/ssl/tls.crt
  key_file = /etc/dovecot/ssl/tls.key
}

mail_attribute {
  dict file {
    path = %{home}/dovecot-attributes
  }
}

log_path = /dev/stdout

imap_hibernate_timeout = 5s

mail_plugins {
  fts = yes
  fts_flatcurve = yes
  mail_log = yes
  notify = yes
}

mail_log_events = delete undelete expunge save copy mailbox_create mailbox_delete mailbox_rename flag_change

fts_autoindex = yes
fts_autoindex_max_recent_msgs = 999
fts_search_add_missing = yes
language_filters = normalizer-icu snowball stopwords

language_tokenizers = generic email-address
language_tokenizer_generic_algorithm = simple

language en {
  default = yes
  filters = lowercase snowball english-possessive stopwords
}

fts flatcurve {
  substring_search = yes
}

protocol imap {
  mail_plugins {
     imap_sieve = yes
     imap_filter_sieve = yes
  }
}

protocol lmtp {
   mail_plugins {
      sieve = yes
   }
}

service imap-login {
  process_min_avail = 1
  client_limit = 100
}

service pop3-login {
  process_min_avail = 1
  client_limit = 100
}

service submission-login {
  process_min_avail = 1
  client_limit = 100
}

service managesieve-login {
  process_min_avail = 1
  client_limit = 100
}

service lmtp {
   inet_listener lmtps {
     port = 31024
     ssl = no
   }
}

event_exporter log {
   format = json
   time_format = rfc3339
}

service pop3-login {
}

protocols {
  pop3 = yes
}

service auth {
  inet_listener auth {
    port = 12345
  }
}

#auth_debug = yes
#auth_debug_passwords = yes

sql_driver = mysql
passdb_default_password_scheme = SHA512-CRYPT
passdb sql {
  query = SELECT local_part AS username, domain, password FROM mailbox WHERE local_part = '%{user | username}' AND domain = '%{user | domain}' AND active='1'
}
userdb sql {
  query = SELECT CONCAT('/srv/vmail/', maildir) AS home, 1000 AS uid, 1000 AS gid, CONCAT(quota, 'B') AS quota_storage_size FROM mailbox WHERE local_part = '%{user | username}' AND domain = '%{user | domain}' AND active='1'
}

!include_try vendor.d/*.conf
!include_try conf.d/*.conf
